POST https://webapieb2025.azurewebsites.net/rabate
Content-Type: application/json
 
{
    "input": 30
}

POST http://localhost:3000/calculateNetValue
Content-Type: application/json

{
    "price": 100
}